# fly.toml app configuration file generated for hackernews-be on 2024-05-16T23:02:32+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hackernews-be'
primary_region = 'sin'
console_command = '/rails/bin/rails console'

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
size = 'shared-cpu-1x'
memory = 256
