name: Test

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby and dependencies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.0
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Run tests
        run: RUBYOPT='-W0' bundle exec rspec spec

      - name: Upload coverage results
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: coverage-report
          path: coverage